### ISSUE TITLE
Custom URL Path

### ISSUE THREAD

**Issue by Icyscools** [max180643/R-CHNWT#1]
### Feature Request: Custom URL Path

I want to custom URL path because easier to remember. 
This can leading to tell user by URL path to acknowledge what it about.

Currently, this project will generate 5 random character to create short URL for our request
but sometime it tend to be hard to remember from randomness.

***There is example of custom URL path***
I want to shorten URL of Google ([https://google.com](https://google.com)). 
Currently, It would shorten with randomness with this post request to `/url`
```
// post request to '/url' path
{
    "url": "https://google.com"
}
```
and It'll response as
```
{
    "status": "success",
    "id": "kAisY",
    "shortUrl": "https://r.chnwt.dev/kAisY",
    "fullUrl": "https://google.com"
}
```
---
*With custom URL path.*
It should be post request to `/url` path by this request body
```
// post request to '/url' path
{
    "url": "https://google.com",
    "custom_path": "google"
}
```
and It should response as
```
{
    "status": "success",
    "id": "google",
    "shortUrl": "https://r.chnwt.dev/google",
    "fullUrl": "https://google.com"
}
```
but if we already have custom URL path in our database, it should throw error response as
```
{
    "status": "failure",
    "response": "This custom URL path already used."
}
```

**Comment by max180643** [comment]
@Icyscools, Thank you for your suggestion.

https://github.com/max180643/R-CHNWT/commit/0cc5e5d64bae48896b852743da1a72365f4fa136 **:sparkles: add create shortened URL with custom alias**
